[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x484c52"
blue = "0x96b1c9"
cyan = "0x9fc9c3"
green = "0xdffebe"
magenta = "0xbfa5c7"
red = "0xd27c7b"
white = "0xfcf7e2"
yellow = "0xf0d189"

[colors.cursor]
cursor = "0xffffff"
text = "0x000000"

[colors.normal]
black = "0x35383b"
blue = "0x7693ac"
cyan = "0x749e99"
green = "0x769972"
magenta = "0x977ba0"
red = "0xb05655"
white = "0x848b92"
yellow = "0xe1a574"

[colors.primary]
background = "0x111111"
foreground = "0xeaeaea"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "On"

[env]
TERM = "alacritty"

[font]
size = 11.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "K"
mods = "Command"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[general]
live_config_reload = true

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = """,â”‚`|:"' ()[]{}<>"""

[window]
decorations = "full"
dynamic_padding = false

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 2
y = 2
